### ISSUE TITLE
According to ensime guys, this build is "broken"

### ISSUE THREAD

**Issue by mdedetrich** [scala-js/scalajs-cross-compile-example#7]
Referring to the comments here https://github.com/ensime/ensime-sbt/issues/138#issuecomment-216038070 and https://github.com/ensime/ensime-sbt/issues/138#issuecomment-216038257 and in the https://github.com/ensime/ensime-sbt/issues/138 in general, it appears that the Scala.js cross compile project is "broken" according to @fommil.

No idea what the real cause of the issue is (according to @fommil you need to have your `scalaVersion` defined on the global top level), however this doesn't fix the problem either way when you try to adjust this sample and move `scalaVersion` to the top level. It might be the Scala.js auto plugin changing things around.

**Comment by fommil** [comment]
```
> show scalaVersion
[info] fooJS/*:scalaVersion
[info] 	2.11.6
[info] fooJVM/*:scalaVersion
[info] 	2.11.6
[info] root/*:scalaVersion
[info] 	2.10.4
```

i.e. your build is broken.

The correct fix for the majority of sbt users is at the top of https://github.com/ensime/ensime-sbt/issues/138

I can confirm that it doesn't work for this project. A workaround for you is to add 

```
    scalaVersion := "2.11.6"
```

to your `root` definition, but there is definitely something funky happening with the `crossProject`

**Comment by sjrd** [comment]
Neither `ScalaJSPlugin` nor `crossProject` set the `scalaVersion` nor `scalaCrossVersions` of builds. Therefore, Scala.js itself is not interfering with this, and the "recommended fix" should work.

Maybe try `scalaVersion in ThisBuild` or `scalaVersion in Global` instead of just `scalaVersion`.

That said, I do disagree with Ensime guys on this build being "broken". At the sbt level, nothing prevents separate subprojects from having different `scalaVersion`s. It is even *necessary* if you have an sbt plugin as one of the subprojects, as is the case for [this build file](https://github.com/sjrd/scalajs-reflect/blob/master/build.sbt), for example.

Saying that builds with different `scalaVersion`s for different subprojects are "broken" is only true according to Ensime's arbitrary restrictions on what a "correct" build means.

Now, I do not want to fight this fight. It is inevitably going to enter into circles where Ensime people and myself claim that the other party is wrong and should fix things on their side. If there is something we can do about the build file of this project to make Ensime happy, I'm fine with doing it. If there isn't, well, either someone proves to me there's something we can change in `CrossProject` that would "make it work" (without destroying the other features), or ... well ... there is no solution.

**Comment by fommil** [comment]
builds that have two versions of scala are going to come across all kinds of problems, both in their published artefacts and any usage of sbt plugin that depends on the scala version. Unless you really intended to have two versions of scala in your project, then doing so is wrong. Where is the `crossProject` object defined? I can take a look at it.

**Comment by fommil** [comment]
btw, `scalaVersion in ThisBuild := "2.11.8"` does fix it, I'll recommend that on our side and I hope you can update your documentation as well so that you don't advise per-`Project` `scalaVersion`s.

**Comment by fommil** [comment]
@sjrd are you perhaps using the `settings` constructor of `Project` anywhere? That is a well-known cause of this problem and, as such, sbt 0.13.12 is deprecating it and 1.0 is removing the ability to access it altogether.

**Comment by sjrd** [comment]
> builds that have two versions of scala are going to come across all kinds of problems, both in their published artefacts and any usage of sbt plugin that depends on the scala version.

That is not true. It is only true *if* there is any dependency relationship between a 2.10 project and a 2.11 project. But there need not be dependency relationships among *all* projects of an sbt build. Once again, see [this build file](https://github.com/sjrd/scalajs-reflect/blob/master/build.sbt) for a perfectly good build with two different Scala versions.

> Where is the crossProject object defined? I can take a look at it.

https://github.com/scala-js/scala-js/blob/master/sbt-plugin/src/main/scala/scala/scalajs/sbtplugin/cross/CrossProject.scala

> btw, scalaVersion in ThisBuild := "2.11.8" does fix it, I'll recommend that on our side and I hope you can update your documentation as well so that you don't advise per-Project scalaVersions.

Sure, if that fixes it, as I said, I'm happy to take a PR with that fix. Also I'll take a PR to update this page: https://www.scala-js.org/doc/project/cross-build.html

> are you perhaps using the settings constructor of Project anywhere?

No, we are not. We are well aware of the "problems" caused by the `Project` constructor.

**Comment by fommil** [comment]
that's really interesting, https://github.com/scala-js/scala-js/blob/master/sbt-plugin/src/main/scala/scala/scalajs/sbtplugin/cross/CrossProject.scala#L296 you are indeed not using the `settings` constructor parameter. I have no idea why this is requiring sbt to define the extra `in ThisBuild`. Presumably this means that any top-level settings that the user provides are not inherited by the submodules? Is that the case for multi-project builds in general or just scalajs ones?

**Comment by fommil** [comment]
@mdedetrich since you found and reported it, can you please send the PR to the documentation locations noted above by Sebastien? If somebody needs multi-scala versions in their build, they probably know what they are doing and would be prepared for things breaking, it shouldn't be the fallback.

**Comment by sjrd** [comment]
> Presumably this means that any top-level settings that the user provides are not inherited by the submodules? Is that the case for multi-project builds in general or just scalajs ones?

Settings defined at the "top-level" of a multi-project build are in fact part of the *root* subproject. There are not defined in the project-agnostic scope (`ThisBuild`), as most people think they are.

**Comment by fommil** [comment]
ah ok. I've been using `.scala` files for multi-project and the `settings` there are inherited. This is indeed a common misconception, so we should certainly be using `something in ThisBuild = "foo"` as much as possible in our (collective) docs to explain.

**Comment by mdedetrich** [comment]
Pull request is here https://github.com/scala-js/scalajs-cross-compile-example/pull/8

I have also bumped the version of Scala and Scala.js

**Comment by fommil** [comment]
@mdedetrich don't forget to PR the docs as well as Sebastien notes above. I'm not sure which repo that is in.

**Comment by mdedetrich** [comment]
Here is the PR for the docs https://github.com/scala-js/scala-js-website/pull/273
